"""add split

Revision ID: 2f1650e30d53
Revises: 5c5164f4a120
Create Date: 2022-06-14 12:32:15.465690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1650e30d53'
down_revision = '5c5164f4a120'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sc', sa.String(length=128), nullable=True),
    sa.Column('split_date', sa.Date(), nullable=True),
    sa.Column('split_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_splits_id'), 'stock_splits', ['id'], unique=False)
    op.create_index(op.f('ix_stock_splits_sc'), 'stock_splits', ['sc'], unique=False)
    op.create_index(op.f('ix_stock_splits_split_date'), 'stock_splits', ['split_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_splits_split_date'), table_name='stock_splits')
    op.drop_index(op.f('ix_stock_splits_sc'), table_name='stock_splits')
    op.drop_index(op.f('ix_stock_splits_id'), table_name='stock_splits')
    op.drop_table('stock_splits')
    # ### end Alembic commands ###
