"""change stocks

Revision ID: 5c5164f4a120
Revises: 8204aeca159e
Create Date: 2022-06-09 13:49:38.652922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c5164f4a120'
down_revision = '8204aeca159e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('sc', sa.String(length=128), nullable=True))
    op.add_column('stocks', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('stocks', sa.Column('market', sa.String(length=128), nullable=True))
    op.add_column('stocks', sa.Column('industry', sa.String(length=128), nullable=True))
    op.add_column('stocks', sa.Column('opened_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('closed_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('transaction_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('market_capitalization', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('low_limit', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('high_limit', sa.Float(), nullable=True))
    op.drop_index('ix_stocks_company_code', table_name='stocks')
    op.create_index(op.f('ix_stocks_industry'), 'stocks', ['industry'], unique=False)
    op.create_index(op.f('ix_stocks_market'), 'stocks', ['market'], unique=False)
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    op.create_index(op.f('ix_stocks_sc'), 'stocks', ['sc'], unique=False)
    op.drop_column('stocks', 'company_code')
    op.drop_column('stocks', 'close_price')
    op.drop_column('stocks', 'open_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('open_price', mysql.FLOAT(), nullable=True))
    op.add_column('stocks', sa.Column('close_price', mysql.FLOAT(), nullable=True))
    op.add_column('stocks', sa.Column('company_code', mysql.VARCHAR(length=128), nullable=True))
    op.drop_index(op.f('ix_stocks_sc'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_market'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_industry'), table_name='stocks')
    op.create_index('ix_stocks_company_code', 'stocks', ['company_code'], unique=False)
    op.drop_column('stocks', 'high_limit')
    op.drop_column('stocks', 'low_limit')
    op.drop_column('stocks', 'market_capitalization')
    op.drop_column('stocks', 'transaction_price')
    op.drop_column('stocks', 'closed_price')
    op.drop_column('stocks', 'opened_price')
    op.drop_column('stocks', 'industry')
    op.drop_column('stocks', 'market')
    op.drop_column('stocks', 'name')
    op.drop_column('stocks', 'sc')
    # ### end Alembic commands ###
