"""add stock

Revision ID: 8204aeca159e
Revises: 1ba07afa330a
Create Date: 2022-06-04 05:19:50.538313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8204aeca159e"
down_revision = "1ba07afa330a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_code", sa.String(length=128), nullable=True),
        sa.Column("b_date", sa.Date(), nullable=True),
        sa.Column("open_price", sa.Float(), nullable=True),
        sa.Column("close_price", sa.Float(), nullable=True),
        sa.Column("high_price", sa.Float(), nullable=True),
        sa.Column("low_price", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stocks_b_date"), "stocks", ["b_date"], unique=False)
    op.create_index(
        op.f("ix_stocks_company_code"), "stocks", ["company_code"], unique=False
    )
    op.create_index(op.f("ix_stocks_id"), "stocks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_id"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_company_code"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_b_date"), table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
